Repository micronaut-projects/micronaut-kafka, pull requests merged in 2022-11, with the labels that each got.

#585 [kafka] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#618 [kafka] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#513 GH-227 adds all tags available from kafka metrics
  kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetricsReporter.java
  kafka/src/main/java/io/micronaut/configuration/kafka/metrics/ConsumerKafkaMetricsReporter.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaConsumerMetricsSpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaProducerMetricsSpec.groovy
Labels: type: improvement

#591 use the original group id for loading consumer configuration first
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
Labels: type: bug

#592 Error Strategy retry on specifics exceptions
  kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  src/main/docs/guide/kafkaListener/kafkaErrors.adoc
Labels: type: enhancement
