Repository micronaut-projects/micronaut-kafka, pull requests merged in 2023-07, with the labels that each got.

#759 [kafka] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#766 Add new config property `ErrorStrategy.handleAllExceptions`
  kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategy.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy
Labels: type: improvement

#768 Kafka to Micronaut Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#773 Kafka no milestones
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#775 Remove baseline version for binary compatibility check
  buildSrc/src/main/groovy/io.micronaut.build.internal.kafka-module.gradle
Labels: relates-to: build

#772 Replace deprecated method call `findArgumentBinder`
  kafka/src/main/java/io/micronaut/configuration/kafka/bind/batch/BatchConsumerRecordsBinderRegistry.java
Labels: type: improvement

#774 Kafka health checks and topics replication
  kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaHealthIndicatorSpec.groovy
Labels: type: improvement

#771 Catch record deserialization exceptions that may happen while polling
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorStrategySpec.groovy
Labels: type: bug

#777 Update guide ("Embedding Kafka" -> "Dockerizing Kafka")
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/kafkaClient/kafkaClientScope.adoc
  src/main/docs/guide/kafkaClient/kafkaDockerized.adoc
  src/main/docs/guide/kafkaClient/kafkaEmbedded.adoc
  src/main/docs/guide/toc.yml
  test-suite-groovy/build.gradle.kts
  test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/AbstractKafkaTest.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/MyTest.groovy
  test-suite-kotlin/build.gradle.kts
  test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/AbstractKafkaTest.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/MyTest.kt
  test-suite/build.gradle.kts
  test-suite/src/test/java/io/micronaut/kafka/docs/AbstractKafkaTest.java
  test-suite/src/test/java/io/micronaut/kafka/docs/MyTest.java
Labels: type: docs

#785 [kafka] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#791 [kafka] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#782 CI never ends for unit tests with manual test container lifecycle control
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/MyTest.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/MyTest.kt
  test-suite/src/test/java/io/micronaut/kafka/docs/MyTest.java
Labels: type: bug
