Repository micronaut-projects/micronaut-kafka, pull requests merged in 2023-09, with the labels that each got.

#850 use reactor instead of rxjava2
  buildSrc/src/main/groovy/io.micronaut.internal.build.kafka-testsuite.gradle
  gradle/libs.versions.toml
  kafka/build.gradle
  kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaBatchListenerSpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaReactiveListenerSpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaSendToSpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/health/KafkaProducerMetricsSpec.groovy
  settings.gradle
  src/main/docs/guide/kafkaClient/kafkaClientBatch.adoc
  src/main/docs/guide/kafkaClient/kafkaClientMethods.adoc
  src/main/docs/guide/kafkaListener/kafkaListenerBatch.adoc
  src/main/docs/guide/kafkaListener/kafkaListenerMethods.adoc
  test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/batch/BookClient.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/reactive/ProductListener.groovy
  test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/producer/methods/BookClient.groovy
  test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/batch/BookClient.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/reactive/ProductListener.kt
  test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/producer/methods/BookClient.kt
  test-suite/src/test/java/io/micronaut/kafka/docs/consumer/batch/BookClient.java
  test-suite/src/test/java/io/micronaut/kafka/docs/consumer/reactive/ProductListener.java
  test-suite/src/test/java/io/micronaut/kafka/docs/producer/methods/BookClient.java
Labels: type: docs

#864 Prevent consumers with duplicate client IDs from shadowing each other
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/ConsumerRegistrySpec.groovy
Labels: type: bug

#865 Honor `transactionalId` when a Kafka producer bean is injected
  kafka/src/main/java/io/micronaut/configuration/kafka/KafkaProducerFactory.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaTxSpec.groovy
Labels: type: bug

#869 [kafka] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#878 Normalize producer client ID to find configuration bean
  kafka/src/main/java/io/micronaut/configuration/kafka/KafkaProducerFactory.java
  kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaProducerFactorySpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/config/KafkaProducerConfigurationSpec.groovy
Labels: type: bug

#871 Refactor `KafkaConsumerProcessor`
  kafka/src/main/java/io/micronaut/configuration/kafka/annotation/ErrorStrategyValue.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerCloseState.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerInfo.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerSeekAwareAdapter.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/ConsumerState.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/FluxCallback.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/MonoCallback.java
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/PartitionRetryState.java
Labels: type: improvement

#876 Normalize consumer group ID to find configuration bean
  kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaConfigurationSpec.groovy
Labels: type: bug
