Repository micronaut-projects/micronaut-kafka, pull requests merged in 2024-10, with the labels that each got.

#1071 [kafka] Update common files for branch 5.7.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#1088 Make KStream health result serializable (#1026)
  kafka-streams/build.gradle
  kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/health/serde/TaskIdSerde.java
  kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/health/serde/TaskIdSerdeSpec.groovy
Labels: type: enhancement

#1093 Upgrade to Kafka 3.8
  gradle/libs.versions.toml
  kafka-bom/build.gradle
  kafka/src/main/java/io/micronaut/configuration/kafka/health/DefaultNetworkClientCreator.java
  kafka/src/main/java/io/micronaut/configuration/kafka/health/KafkaHealthIndicator.java
  kafka/src/test/groovy/io/micronaut/configuration/kafka/KafkaConfigurationSpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaTypeConversionSpec.groovy
  kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaBatchErrorStrategySpec.groovy
Labels: type: dependency-upgrade
